package smoke

fun main() {
    println("annotated ${annotated.box()}")
    println("arrayAccess ${arrayAccess.box()}")
    println("arrayAssignment ${arrayAssignment.box()}")
    println("branches ${branches.box()}")
    println("callableReference ${callableReference.box()}")
    println("calls ${calls.box()}")
    println("classReference ${classReference.box()}")
    println("destructuring ${destructuring.box()}")
    println("for ${_for.box()}")
    println("genericCalls ${genericCalls.box()}")
    println("in ${_in.box()}")
    println("inBrackets ${inBrackets.box()}")
    println("init ${init.box()}")
    println("labelForInfix ${labelForInfix.box()}")
    println("lambda ${lambda.box()}")
    println("lambdaAndAnonymousFunction ${lambdaAndAnonymousFunction.box()}")
    println("locals ${locals.box()}")
    println("modifications ${modifications.box()}")
    println("namedArguments ${namedArguments.box()}")
    println("nullability ${nullability.box()}")
    println("qualifierWithTypeArguments ${qualifierWithTypeArguments.box()}")
    println("simpleReturns ${simpleReturns.box()}")
    println("super ${_super.box()}")
    println("these ${these.box()}")
    println("try ${_try.box()}")
    println("typeOperators ${typeOperators.box()}")
    println("unary ${unary.box()}")
    println("variables ${variables.box()}")
    println("while ${_while.box()}")
}